# Task
Deduce the Normal Equation for a linear regression model with two predictor variables and find the least square parabola which fits the data: X = [0, 1, 2, 3, 4, 5, 6] and Y = [3.4, 3.9, 4.2, 6.6, 10.3, 14.6, 21.9].

In [1]:
import numpy as np

X_data = np.array([0, 1, 2, 3, 4, 5, 6])
Y_data = np.array([3.4, 3.9, 4.2, 6.6, 10.3, 14.6, 21.9])

print("X_data:", X_data)
print("Y_data:", Y_data)

X_data: [0 1 2 3 4 5 6]
Y_data: [ 3.4  3.9  4.2  6.6 10.3 14.6 21.9]


In [9]:
ones_column = np.ones_like(X_data)
X_column = X_data
X_squared_column = X_data**2
A = np.column_stack((ones_column, X_column, X_squared_column))
print("Design Matrix A:")
print(A)

Design Matrix A:
[[ 1  0  0]
 [ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]
 [ 1  6 36]]


In [10]:
A_transpose = A.T
A_transpose_A = A_transpose @ A
A_transpose_A_inv = np.linalg.inv(A_transpose_A)
A_transpose_Y = A_transpose @ Y_data
W = A_transpose_A_inv @ A_transpose_Y

print("Parameters W:", W)


Parameters W: [ 3.74761905 -1.07857143  0.67380952]


In [11]:
print(f"The calculated parameters (W) for the least square parabola are: {W}")
print(f"The equation of the least square parabola is: Y = {W[0]:.4f} + {W[1]:.4f}*X + {W[2]:.4f}*X^2")

The calculated parameters (W) for the least square parabola are: [ 3.74761905 -1.07857143  0.67380952]
The equation of the least square parabola is: Y = 3.7476 + -1.0786*X + 0.6738*X^2


In [12]:
import numpy as np

X_data = np.array([0, 1, 2, 3, 4, 5, 6])
Y_data = np.array([3.4, 3.9, 4.2, 6.6, 10.3, 14.6, 21.9])

print("X_data:", X_data)
print("Y_data:", Y_data)

X_data: [0 1 2 3 4 5 6]
Y_data: [ 3.4  3.9  4.2  6.6 10.3 14.6 21.9]


In [13]:
ones_column = np.ones_like(X_data)
X_column = X_data
X_squared_column = X_data**2
A = np.column_stack((ones_column, X_column, X_squared_column))
print("Design Matrix A:")
print(A)

Design Matrix A:
[[ 1  0  0]
 [ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]
 [ 1  6 36]]


In [14]:
A_transpose = A.T
A_transpose_A = A_transpose @ A
A_transpose_A_inv = np.linalg.inv(A_transpose_A)
A_transpose_Y = A_transpose @ Y_data
W = A_transpose_A_inv @ A_transpose_Y

print("Parameters W:", W)


Parameters W: [ 3.74761905 -1.07857143  0.67380952]


In [15]:
print(f"The calculated parameters (W) for the least square parabola are: {W}")
print(f"The equation of the least square parabola is: Y = {W[0]:.4f} + {W[1]:.4f}*X + {W[2]:.4f}*X^2")

The calculated parameters (W) for the least square parabola are: [ 3.74761905 -1.07857143  0.67380952]
The equation of the least square parabola is: Y = 3.7476 + -1.0786*X + 0.6738*X^2
